config/routes.rb
Rails.application.routes.draw do
   require 'sidekiq/web'
   authenticate :user, lambda { |u| u.is_admin? } do
     mount Sidekiq::Web => '/sidekiq'
   end
  devise_for :users
  resource :user


  resources :events do
    resources :registrations do
      member do
        get 'steps/1', to: 'registrations#step1', as: :step1
        patch 'steps/1/update', to: 'registrations#step1_update', as: :update_step1
        get 'steps/2', to: 'registrations#step2', as: :step2
        patch 'steps/2/update', to: 'registrations#step2_update', as: :update_step2
        get 'steps/3', to: 'registrations#step3', as: :step3
        patch 'steps/3/update', to: 'registrations#step3_update', as: :update_step3
      end
    end
  end

  namespace :admin do
    root "events#index"
    resources :versions do
      post :undo
    end
    resources :events do
      resources :registration_imports
      resources :registrations, :controller => "event_registrations" do
        collection do
          post :import
        end
      end
      resources :tickets, controller: 'event_tickets'
      member do
        post :reorder
      end
      collection do
        post :bulk_update
      end
    end
    resources :users do
      resource :profile, controller: 'user_profiles'
    end
  end

  get '/faq', to: 'pages#faq'

  root "events#index"

end

app/models/event.rb
class Event < ApplicationRecord

 validates_presence_of :name
 validates :friendly_id, presence: true, uniqueness: true, format: { with: /\A[a-z0-9\-]+\z/ }
 # validates_presence_of :name, :friendly_id

 # validates_uniqueness_of :friendly_id
 # validates_format_of :friendly_id, :with => /\A[a-z0-9\-]+\z/

 before_validation :generate_friendly_id, on: :create
 belongs_to :category, optional: true
 has_many :tickets, dependent: :destroy, inverse_of: :event
 accepts_nested_attributes_for :tickets, allow_destroy: true, reject_if: :all_blank
 has_many :registrations, dependent: :destroy
 has_many :registration_imports, :dependent => :destroy

  has_many :attachments, :class_name => "EventAttachment", :dependent => :destroy
  accepts_nested_attributes_for :attachments, :allow_destroy => true, :reject_if => :all_blank

 mount_uploader :logo, EventLogoUploader
 mount_uploaders :images, EventImageUploader
 serialize :images, JSON

 STATUS = ['draft', 'public', 'private']
 validates :status, inclusion: STATUS

 include RankedModel
 ranks :row_order

 scope :only_public, -> { where( :status => "public" ) }
 scope :only_available, -> { where( :status => ["public", "private"] ) }

 def to_param
   self.friendly_id
 end

 protected

 def generate_friendly_id
   self.friendly_id || SecureRandom.uuid
 end
end

app/controllers/admin/event_registrations_controller.rb
require 'csv'
class Admin::EventRegistrationsController < AdminController
  before_action :find_event
  before_action :require_editor!

  def index
    # @registrations = @event.registrations.includes(:ticket).order('id DESC').page(params[:page])
    @q = @event.registrations.ransack(params[:q])
    @registrations = @q.result.includes(:ticket).order('id DESC').page(params[:page])

    if params[:status].present? && Registration::STATUS.include?(params[:status])
      @registrations = @registrations.by_status(params[:status])
    end

    if params[:ticket_id].present?
      @registrations = @registrations.by_ticket(params[:ticket_id])
    end
    if Array(params[:statuses]).any?
      @registrations = @registrations.by_status(params[:statuses])
    end

    if Array(params[:ticket_ids]).any?
      @registrations = @registrations.by_ticket(params[:ticket_ids])
    end
    if params[:start_on].present?
      @registrations = @registrations.where( "created_at >= ?", Date.parse(params[:start_on]).beginning_of_day )
    end

    if params[:end_on].present?
      @registrations = @registrations.where( "created_at <= ?", Date.parse(params[:end_on]).end_of_day )
    end
    if params[:registration_id].present?
      @registrations = @registrations.where( :id => params[:registration_id].split(",") )
    end

    respond_to do |format|
      format.html
      format.csv {
        @registrations = @registrations.reorder("id ASC")
        csv_string = CSV.generate do |csv|
          csv << ["报名ID", "票种", "姓名", "状态", "Email", "报名时间"]
          @registrations.each do |r|
            csv << [r.id, r.ticket.name, r.name, t(r.status, :scope => "registration.status"), r.email, r.created_at]
          end
        end
        send_data csv_string, :filename => "#{@event.friendly_id}-registrations-#{Time.now.to_s(:number)}.csv"
      }
      format.xlsx
    end
  end

  def destroy
    @registration = @event.registrations.find_by_uuid(params[:id])
    @registration.destroy

    redirect_to admin_event_registrations_path(@event)
  end

  def import
    csv_string = params[:csv_file].read.force_encoding('utf-8')

    tickets = @event.tickets

    success = 0
    failed_records = []

    CSV.parse(csv_string) do |row|
      registration = @event.registrations.new( :status => "confirmed",
                                   :ticket => tickets.find{ |t| t.name == row[0] },
                                   :name => row[1],
                                   :email => row[2],
                                   :cellphone => row[3],
                                   :website => row[4],
                                   :bio => row[5],
                                   :created_at => Time.parse(row[6]) )

      if registration.save
        success += 1
      else
        failed_records << [row, registration]
        Rails.logger.info("#{row} ----> #{registration.errors.full_messages}")
      end
    end

    flash[:notice] = "总共汇入 #{success} 笔，失败 #{failed_records.size} 笔"
    redirect_to admin_event_registrations_path(@event)

  end

  protected

  def find_event
    @event = Event.find_by_friendly_id!(params[:event_id])
  end

  def registration_params
    params.require(:registration).permit(:status, :ticket_id, :name, :email, :cellphone, :website, :bio)
  end
end

app/helpers/admin/event_registrations_helper.rb
module Admin::EventRegistrationsHelper

  def registration_filters(options)
    params.permit(:status, :ticket_id).merge(options)
  end
end

app/views/admin/event_registrations/index.html.slim
h1
  => @event.name
  | / Registrations

p.text-right
   = link_to 'New Registration', new_admin_event_registration_path(@event), class: 'btn btn-primary'
   = link_to "Import Registration", admin_event_registration_imports_path(@event), :class => "btn btn-primary"

- if false
  .submenu
    .btn-group
      = link_to "All (#{@event.registrations.size})", admin_event_registrations_path(registration_filters(status: nil)), class: "btn btn-suceess btn-group #{display_status?}"
      - Registration::STATUS.each do |s|
        = link_to t(s, scope: 'registration.status') + "(#{@event.registrations.by_status(s).size})", admin_event_registrations_path(registration_filters(status: s)), class: "btn btn-success btn-group #{display_status_active? s}"
    .btn-group
      = link_to "All (#{@event.registrations.size})", admin_event_registrations_path(registration_filters(ticket_id: nil)), class: "btn btn-suceess btn-group #{display_ticket_id?}"
      - @event.tickets.each do |t|
        = link_to t.name + "(#{@event.registrations.by_ticket(t).size})", admin_event_registrations_path(registration_filters(ticket_id: t.id)), class: "btn btn-success btn-group #{display_status_active? t}"


# = form_tag admin_event_registrations_path(@event), method: :get do
= search_form_for @q, url: admin_event_registrations_path(@event) do |f|
  p
    = f.search_field :name_cont, placeholder: 'name', class: 'form-control'
  p
    = f.search_field :email_cont, placeholder: 'email', class: 'form-control'
  p
    = text_field_tag :registration_id, params[:registration_id], placeholder: '报名编号， 可用“，”分隔'
  p
    - Registration::STATUS.each do |s|
      label
        = check_box_tag 'statuses[]', s, Array(params[:statuses]).include?(s)
        = t(s, scope: 'registration.status') + "(#{@event.registrations.by_status(s).size})"
  p
    - @event.tickets.each do |t|
      label
        = check_box_tag 'ticket_ids[]', t.id, Array(params[:ticket_ids]).include?(t.id.to_s)
        = t.name + "(#{@event.registrations.where(ticket_id: t.id).size}"

  p
    | date
    =< date_field_tag :start_on, params[:start_on]
    =< date_field_tag :end_on, params[:end_on]

  p.text-right
    = submit_tag 'Send', class: 'btn btn-primary'

table.table
  thead
    tr
      th ID
      th Ticket
      th Name
      th Status
      th E-mail
      th 建立时间
      th Actions
  tbody
    - @registrations.each do |registration|
      tr
        td = registration.id
        td = registration.ticket.name
        td = registration.name
        td = t(registration.status, scope: 'registration.status')
        td = registration.email
        td = registration.created_at
        td
          = link_to 'Edit', edit_admin_event_registration_path(@event, registration), class: 'btn btn-default'
          = link_to 'Delete', admin_event_registration_path(@event, registration), method: :delete, data: { confirm: 'Are you sure?' },
          class: 'btn btn-default'
= paginate @registrations
p
  = link_to 'export CSV', admin_event_registrations_path(format: :csv), class: 'btn btn-default'
  = link_to "汇出 Excel", admin_event_registrations_path(:format => :xlsx), :class => "btn btn-default"
hr
= form_tag import_admin_event_registrations_path(@event), :multipart => true do
  p
    = file_field_tag "csv_file"
  p
    = submit_tag "汇入CSV", :class => "btn btn-danger"