config/routes.rb
Rails.application.routes.draw do
   require 'sidekiq/web'
   authenticate :user, lambda { |u| u.is_admin? } do
     mount Sidekiq::Web => '/sidekiq'
   end
  devise_for :users
  resource :user


  resources :events do
    resources :registrations do
      member do
        get 'steps/1', to: 'registrations#step1', as: :step1
        patch 'steps/1/update', to: 'registrations#step1_update', as: :update_step1
        get 'steps/2', to: 'registrations#step2', as: :step2
        patch 'steps/2/update', to: 'registrations#step2_update', as: :update_step2
        get 'steps/3', to: 'registrations#step3', as: :step3
        patch 'steps/3/update', to: 'registrations#step3_update', as: :update_step3
      end
    end
  end

  namespace :admin do
    root "events#index"
    resources :versions do
      post :undo
    end
    resources :events do
      resources :registration_imports
      resources :registrations, :controller => "event_registrations" do
        collection do
          post :import
        end
      end
      resources :tickets, controller: 'event_tickets'
      member do
        post :reorder
      end
      collection do
        post :bulk_update
      end
    end
    resources :users do
      resource :profile, controller: 'user_profiles'
    end
  end

  get '/faq', to: 'pages#faq'

  root "events#index"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :memberships
  has_many :groups, through: :memberships
  has_one :profile
  accepts_nested_attributes_for :profile
  has_many :registrations
  ROLES = ["admin", "editor"]

  def display_name
    self.email.split("@").first
  end


  def is_admin?
    self.role == "admin"
  end

  def is_editor?
    ["admin", "editor"].include?(self.role)  # 如果是 admin 的话，当然也有 editor 的权限
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :require_admin!

  def index
    @users = User.includes(:groups).all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render 'edit'
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :role, :group_ids => [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user

  def show

  end
  
  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = '修改成功'
      redirect_to edit_user_path
    else
      render 'edit'
    end
  end

  protected

  def user_params
    params.require(:user).permit(:time_zone, :profile_attributs => 
                                [:id, :legal_name, :birthday, :localtion, :education, :occupation, :bio, :specialty])
  end

  def find_user
    @user = current_user
    @user.create_profile unless @user.profile
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.slim
h1 Edit User
- if @user.errors.any?
  #error_explanation
    ul
    - @user.errors.full_messages.each do |msg|
      li = msg
= form_for [:admin, @user] do |f|
  .form-group
    = f.label :email
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :role
    = f.select :role, User::ROLES.map{ |x| [t(x, scope: 'user.role'), x] }, { include_blank: true }, class: 'form-control'
  .form-group
    = f.label :group_ids
    = f.select :group_ids, Group.all.map{ |g| [g.name, g.id] }, {}, multiple: true, class: 'form-control'
  .form-group
    = f.submit 'Update', class: 'btn btn-primary'
    = link_to 'Cancle', admin_users_path

coffee:
  $('#user_group_ids').select2()

app/views/admin/users/index.html.slim
h1 Admin Users

table.table
  thead
    tr
      th ID
      th Email
      th Groups
      th Actions
  tbody
    - @users.each do |user|
      tr
        td = user.id
        td = user.email
        td
          - user.groups.each do |g|
            = g.name
            br
        td = link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-default'
        td = link_to 'Edit Profile', edit_admin_user_profile_path(user), class: 'btn btn-default'